<?php

namespace ProgrammeBundle\Repository;

/**
 * programmeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class programmeRepository extends \Doctrine\ORM\EntityRepository
{
}
