<?php

namespace SalleMatrielBundle\Repository;

/**
 * MatrielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatrielRepository extends \Doctrine\ORM\EntityRepository
{
}
