<?php

namespace SalleMatrielBundle\Repository;

/**
 * typeSalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typeSalleRepository extends \Doctrine\ORM\EntityRepository
{
}
