<?php

namespace EvenementBundle\Repository;

/**
 * TypeEvennementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEvennementRepository extends \Doctrine\ORM\EntityRepository
{
}
