salle_homepage:
    path:     /salle
    defaults: { _controller: SalleMatrielBundle:Default:salle }
matriel_homepage:
    path:     /materiel
    defaults: { _controller: SalleMatrielBundle:Default:materiel }
ajoutSalle:
    path:     /ajoutSalle
    defaults: { _controller: SalleMatrielBundle:Salle:ajoutSalle }
ajoutReservation:
    path:     /ajoutReservation
    defaults: { _controller: SalleMatrielBundle:Reservation:ajoutReservation }