<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQffjcdk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQffjcdk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQffjcdk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQffjcdk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQffjcdk\appDevDebugProjectContainer([
    'container.build_hash' => 'Qffjcdk',
    'container.build_id' => 'a6505074',
    'container.build_time' => 1550387023,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQffjcdk');
