<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMda08x3\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMda08x3/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMda08x3.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMda08x3\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMda08x3\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Mda08x3',
    'container.build_id' => '55995972',
    'container.build_time' => 1550319380,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMda08x3');
